### ISSUE TITLE
Ship with TS declaration file

### ISSUE THREAD

**Issue by jasonkuhrt** [hildjj/node-inspect-extracted#11]
It would be great if a TS declaration file was shipped with the package to support TypeScript development.

**Comment by hildjj** [comment]
Good idea.  I should be able to extract the definition from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/util.d.ts

**Comment by hildjj** [comment]
Fixed in v1.1.0, just released.

**Comment by jasonkuhrt** [comment]
Thanks!
